theme="kaolin-valley-dark"

[editor]
auto-save=false
auto-format=true
auto-completion=true
line-number="relative"
completion-trigger-len=1
# idle-timeout=0
mouse=true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.cursor-shape]
insert="bar"
normal="block"
select="underline"

[editor.statusline]
# left = ["mode", "spinner"]
left = ["mode", "spinner", "file-modification-indicator", "read-only-indicator"]
center = ["file-name"]
# right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
right = ["diagnostics", "register", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.auto-pairs]
'<' = '>'
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[editor.search]
smart-case = true

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
# tabpad = "·"


[editor.lsp]
enable=true
auto-signature-help=true
display-messages = true

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1
