[[language]]
name = "c"
auto-format = false
indent = { tab-width = 4, unit = "    " }


[[language]]
name = "cpp"
auto-format = false
indent = { tab-width = 4, unit = "    " }
#language-server = { command = "clangd"}#, args=["--compile-commands-dir=compile_commands_directory"] }


[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 4, unit = "    " }

roots = [
  "Cargo.toml",
  "Cargo.lock"
]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[language-server.zls]
command = "/Users/dikshant/zls/zig-out/bin"
